Add controllers
SuvorovaElvina/java-shareit pull request #1
Opened 2023-05-04 18:57 UTC by SuvorovaElvina

2023-05-05 17:41 UTC, ohelly requested changes
Привет! Отличная работа, в целом все работает корректно. Есть одно небольшое замечание, которое необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-05-05 17:41 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +public class UserMapper {
Рекомендация: Для создания мапперов рекомендую попробовать такую штуку как мапстракт
https://www.baeldung.com/mapstruct

2023-05-05 17:41 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return repository.getAll().get(id);
Рекомендация: Будет лучше сразу добавить метод поиска по идентификатору в репозиторий. Его также можно будет переиспользовать в методе validateId

2023-05-05 17:41 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        return users;
Рекомендация: Будет лучше если данный метод будет сразу возвращать список, либо делать копию мапы, иначе можно будет изменить данные внутри хранилища извне.

2023-05-05 17:41 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return repository.getAll().get(id);
Рекомендация: Аналогичная рекомендацию по созданию метода поиска по идентификатору. Это также сократит количество запросов в репозиторий, так как можно будет сразу прверять, вернул ли нам репозиторий null или нет.

2023-05-05 17:41 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                if (item.toString().toLowerCase().contains(text.toLowerCase()) && !item.toString().toLowerCase().contains("false")) {
Необходимо исправить: Данную проверку лучше осуществлять напрямую через поля name, description и статусу, так как в названии может быть слово false и тогда вещь не попадет в выдачу.

2023-05-05 17:41 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    public Map<Long, Item> getAll() {
Рекомендация: Аналогичная рекомендация по возвращаему типу. Лучше вернуть сразу лист или сделать копию мапы.

2023-05-05 19:59 UTC, SuvorovaElvina commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +public class UserMapper {
Конфликты с ломбоком, только стало получатся возникла ошибка "возникают проблемы с ArrayList". Я ещё почитаю, постараюсь понять

2023-05-06 18:47 UTC, ohelly approved these changes
Все отлично, исправлены все замечания. Работу принимаю, можно двигаться дальше. Удачи в дальнейшем обучении!

2023-05-06 18:47 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                if (item.toString().toLowerCase().contains(text.toLowerCase()) && !Objects.equals(item.isAvailable(), false)) {
Рекомендация: Вторую проверку можно сократить: ``!item.isAvailable()``

2023-05-06 20:09 UTC, merged